import { createContext, useContext, useState } from 'react';

export const TRACK_IDS = ['software', 'teaching', 'data'];

export const TRACKS = {
  software: {
    id: 'software',
    label: 'Software Engineer',
    portfolioStatement: 'You are viewing my Software Engineer portfolio',
    color: '#2D6BE4',
    accentBg: '#EEF4FF',
    accentBorder: '#BFD3FF',
    heroRoles: ['Full-Stack Developer', 'React Engineer', 'Backend Developer', 'Software Engineer'],
    heroTagline: 'I build fast, scalable web applications.',
    bio: `Full-stack developer and Mathematics graduate student at Missouri State University (GPA 3.73). Over the past 3 years I have built production web applications with React, Node.js, and SQL, including a live crowdfunding platform, a school management system, and a real-time messaging app. My Mathematics background gives me an analytical foundation that complements my engineering experience. Currently based in Springfield, MO and open to remote or in-person software engineering roles.`,
    highlights: [
      { value: '3+',  label: 'Years Building'   },
      { value: '10+', label: 'Projects Shipped'  },
      { value: '10+', label: 'Technologies'      },
    ],
    skills: [
      {
        name: 'Frontend Development',
        icon: 'FaReact',
        level: 'Advanced',
        desc: '3 years of professional experience building production React applications. I work from Figma designs, manage state with Redux, and ship responsive UIs with Tailwind CSS.',
      },
      {
        name: 'Backend Development',
        icon: 'FaNodeJs',
        level: 'Advanced',
        desc: 'Built REST APIs with Node.js and Express in production. Authentication systems, Paystack payment processing, Nodemailer email flows, and database-backed business logic across multiple live applications.',
      },
      {
        name: 'Database Design',
        icon: 'FaDatabase',
        level: 'Advanced',
        desc: '2 years of production experience with MySQL and MongoDB. Designed normalized schemas for a crowdfunding platform and a school management system, with a focus on data integrity.',
      },
      {
        name: 'Secure Authentication',
        icon: 'FaShieldAlt',
        level: 'Advanced',
        desc: 'Implemented JWT-based authentication, bcrypt password hashing, and role-based access control in production applications. Also handled payment webhook verification for financial security.',
      },
      {
        name: 'Real-Time Features',
        icon: 'FaBolt',
        level: 'Intermediate',
        desc: 'Integrated Socket.IO for live messaging in a school communication platform. Comfortable with WebSocket architecture, room management, and event-driven UI updates.',
      },
      {
        name: 'Version Control',
        icon: 'FaGitAlt',
        level: 'Experienced',
        desc: '3 years using Git in professional team environments. Familiar with branching strategies, pull request workflows, and collaborative code review practices.',
      },
      {
        name: 'Problem Solving',
        icon: 'FaLightbulb',
        level: 'Advanced',
        desc: 'Mathematics degree (3.92 GPA, Covenant University) gives me an analytical approach to engineering problems. Strong at edge case analysis, system constraint reasoning, and scalable design.',
      },
      {
        name: 'Responsive Design',
        icon: 'FaMobileAlt',
        level: 'Experienced',
        desc: 'Mobile-first with Tailwind CSS across every application I have built. I test on multiple viewport sizes and treat responsive design as a baseline requirement, not an afterthought.',
      },
    ],
    stack: ['React JS', 'Node.js', 'Express', 'Redux', 'MySQL', 'MongoDB', 'Tailwind CSS', 'JavaScript', 'HTML5', 'CSS3', 'Git', 'GitHub', 'Socket.IO', 'Material UI', 'Bootstrap', 'Vite'],
    projectIds: [1, 2, 3, 4, 5, 6, 7, 8],
    experience: [
      {
        id: 'exp-swe-1',
        role: 'Junior Software Developer',
        company: 'Techvibes International Limited',
        companyUrl: 'https://techvibes.africa',
        logo: 'techvibes',
        location: 'Abuja, Nigeria',
        period: 'Jan 2024 – Dec 2024',
        type: 'Full-time',
        description: 'Built and shipped production features across the frontend and backend for QampusPlus, a school management SaaS platform used by schools across Nigeria.',
        bullets: [
          'Implemented responsive React UI components from Figma designs, improving user experience across the platform.',
          'Integrated RESTful APIs to fetch and display real-time data within frontend applications.',
          'Developed backend features using Node.js and MySQL: user authentication, input validation, payment processing, and email notifications.',
          'Collaborated cross-functionally to translate business requirements into clear, testable implementations.',
        ],
      },
      {
        id: 'exp-swe-2',
        role: 'Software Developer Intern',
        company: 'Techvibes International Limited',
        companyUrl: 'https://techvibes.africa',
        logo: 'techvibes',
        location: 'Abuja, Nigeria',
        period: 'Mar 2022 – Aug 2022',
        type: 'Internship',
        description: 'Full-stack internship focused on building responsive web pages and supporting backend development alongside senior engineers.',
        bullets: [
          'Built responsive and interactive web pages using HTML, CSS, JavaScript, and React.',
          'Supported backend development with Node.js and MySQL, including user authentication and API integration.',
          'Strengthened debugging, testing, and iterative problem-solving skills through real-world development tasks.',
        ],
      },
      {
        id: 'exp-swe-3',
        role: 'Graduate Teaching Assistant',
        company: 'Missouri State University',
        companyUrl: 'https://www.missouristate.edu',
        logo: 'msu',
        location: 'Springfield, MO',
        period: 'Jan 2025 – Present',
        type: 'Part-time',
        description: 'Delivering undergraduate mathematics lectures while pursuing my M.S. in Mathematics.',
        bullets: [
          'Delivered structured undergraduate mathematics lectures, guiding students through rigorous problem-solving.',
          'Provided individualized support to students facing challenges with difficult concepts.',
        ],
      },
    ],
    education: [
      {
        id: 'edu-swe-1',
        degree: 'M.S. Mathematics and Graduate Certificate in Software Engineering',
        school: 'Missouri State University',
        schoolUrl: 'https://www.missouristate.edu',
        logo: 'msu_edu',
        location: 'Springfield, MO',
        period: 'Jan 2025 – Expected Dec 2026',
        gpa: '3.73 / 4.0',
        courses: ['Artificial Intelligence', 'Advanced Internet Programming', 'Data Structures and Algorithms'],
      },
      {
        id: 'edu-swe-2',
        degree: 'B.Sc. Mathematics (Minor: Computer Science)',
        school: 'Covenant University',
        schoolUrl: 'https://covenantuniversity.edu.ng',
        logo: 'covenant',
        location: 'Ogun State, Nigeria',
        period: 'Sept 2019 – Sept 2023',
        gpa: '3.92 / 5.0',
        courses: ['Algorithms and Complexity Analysis', 'Theory of Computing', 'Object-Oriented Programming', 'Structured Programming'],
      },
    ],
    interests: [
      { icon: 'FaSitemap',       label: 'System Design',    desc: 'Thinking about how large-scale systems are architected, how services communicate, and what makes some systems remarkably resilient at scale.' },
      { icon: 'FaRobot',         label: 'AI and ML',        desc: 'Exploring how machine learning models are trained and deployed. Currently taking AI coursework at MSU and learning what is genuinely useful versus overhyped.' },
      { icon: 'MdFunctions',     label: 'Mathematics',      desc: 'Pure and applied mathematics. Number theory, abstract algebra, and the discipline of writing a rigorous proof.' },
      { icon: 'FaPray',          label: 'The Church',       desc: 'An active member of my church community. Faith is central to who I am and how I approach work, relationships, and life.' },
      { icon: 'FaFutbol',        label: 'Football',         desc: 'Lifelong football fan. I follow matches closely, debate tactics, and find the data side of the sport increasingly fascinating.' },
      { icon: 'FaGamepad',       label: 'Gaming',           desc: 'Strategy and puzzle games that challenge pattern recognition and thinking under constraint.' },
    ],
    services: [
      {
        icon: 'FaCode',
        title: 'Web Application Development',
        desc: 'Full-stack applications built with React and Node.js. From user authentication and payment processing to real-time features, I build complete, production-ready systems.',
        deliverables: ['React frontend', 'Node.js and Express backend', 'Database design (MySQL or MongoDB)', 'Authentication and user management', 'Deployment ready'],
      },
      {
        icon: 'FaShoppingCart',
        title: 'E-Commerce Solutions',
        desc: 'Online shops with secure checkout, product management, and order tracking. I have integrated Paystack for live payment processing in real production applications.',
        deliverables: ['Product catalogue and cart', 'Paystack payment integration', 'Order management', 'User accounts and profiles', 'Automated email receipts'],
      },
      {
        icon: 'FaGlobe',
        title: 'Business Websites and Landing Pages',
        desc: 'Professional websites that represent your business clearly and convert visitors into customers. Fully responsive, fast, and built with search visibility in mind.',
        deliverables: ['Custom responsive design', 'Contact and inquiry forms', 'SEO fundamentals', 'Fast load times', 'Mobile-first layout'],
      },
      {
        icon: 'FaUserCircle',
        title: 'Portfolio and Personal Websites',
        desc: 'Personal sites that present your work, skills, and story in a way that gets attention. I know what makes a portfolio stand out because I have built several from scratch.',
        deliverables: ['Multi-section custom layout', 'Project showcases', 'Animated and interactive UI', 'Contact form with email integration', 'Responsive across all devices'],
      },
      {
        icon: 'FaBolt',
        title: 'Real-Time Features and Chat',
        desc: 'Live messaging, notifications, and real-time data updates using Socket.IO. Suitable for team tools, school platforms, or any application that needs instant communication.',
        deliverables: ['WebSocket integration via Socket.IO', 'Room-based messaging', 'User presence indicators', 'Live notifications and updates'],
      },
      {
        icon: 'FaServer',
        title: 'Backend API Development',
        desc: 'Clean, secure REST APIs built with Node.js and Express. Covers authentication, data validation, file uploads, email flows, and third-party service integrations.',
        deliverables: ['REST API design', 'JWT authentication', 'Database integration', 'Webhook and event handling', 'Third-party API integrations'],
      },
    ],
    cvFile: '/CV_Software.pdf',
    cvLabel: 'Software Engineer CV',
  },

  teaching: {
    id: 'teaching',
    label: 'Teaching and Academia',
    portfolioStatement: 'You are viewing my Teaching and Academia portfolio',
    color: '#16A34A',
    accentBg: '#EDFAF3',
    accentBorder: '#86EFAC',
    heroRoles: ['Mathematics Educator', 'Graduate Teaching Assistant', 'Math Tutor', 'Instructor'],
    heroTagline: 'I make mathematics accessible and rigorous.',
    bio: `Graduate Teaching Assistant in the Mathematics Department at Missouri State University (GPA 3.73), delivering undergraduate lectures, running weekly office hours, and providing one-on-one support to students navigating complex topics. I believe rigour and accessibility are not opposites in mathematics teaching. Originally from Nigeria and now based in Springfield, MO, I bring a multicultural perspective and genuine care for student learning alongside academic excellence.`,
    highlights: [
      { value: '3.73', label: 'Graduate GPA'       },
      { value: '1yr+', label: 'Teaching Experience' },
      { value: '3.92', label: 'Undergrad GPA'      },
    ],
    skills: [
      {
        name: 'Undergraduate Lecturing',
        icon: 'FaChalkboardTeacher',
        level: 'Experienced',
        desc: 'Currently delivering undergraduate mathematics lectures at Missouri State University as a Graduate Teaching Assistant. Teaching to mixed-level student groups with varying mathematical backgrounds.',
      },
      {
        name: 'Individualized Student Support',
        icon: 'FaUsers',
        level: 'Experienced',
        desc: 'Weekly office hours and one-on-one sessions with students who are struggling. Most confusion traces back to an earlier conceptual gap rather than the current topic, and I work to find that gap.',
      },
      {
        name: 'Office Hours and Review Sessions',
        icon: 'FaCalendarAlt',
        level: 'Experienced',
        desc: 'Running structured weekly review sessions that reinforce course material. Students build analytical confidence through guided practice and structured repetition over time.',
      },
      {
        name: 'Assessment and Grading',
        icon: 'FaClipboardList',
        level: 'Experienced',
        desc: 'Evaluating student work with clear rubrics that emphasize method over memorization. Detail-oriented and consistent with grading across large student cohorts.',
      },
      {
        name: 'Curriculum Planning',
        icon: 'FaBookOpen',
        level: 'Learning',
        desc: 'Beginning to develop my own lesson structures within the framework set by the department. Working toward the ability to design full course curricula independently.',
      },
      {
        name: 'Abstract Algebra and Number Theory',
        icon: 'MdFunctions',
        level: 'Advanced',
        desc: 'Graduate coursework in Abstract Algebra I and II and Number Theory at MSU. Comfortable teaching proof-based mathematics at an advanced level.',
      },
      {
        name: 'Mentorship and Leadership',
        icon: 'FaUserFriends',
        level: 'Experienced',
        desc: 'Former Vice-President of the National Association of Mathematics Students (NAMSN) at Covenant University. Led mentorship programmes and organized academic support events for peers.',
      },
      {
        name: 'Technology in Teaching',
        icon: 'FaLaptop',
        level: 'Learning',
        desc: 'Proficient in LaTeX for mathematical typesetting. Beginning to incorporate Python for computational demonstrations. Use Brightspace LMS for course administration.',
      },
    ],
    stack: ['LaTeX', 'Python', 'JavaScript', 'R', 'Git', 'GitHub', 'HTML5', 'MySQL', 'React JS'],
    projectIds: [],
    experience: [
      {
        id: 'exp-teach-1',
        role: 'Graduate Teaching Assistant',
        company: 'Missouri State University',
        companyUrl: 'https://www.missouristate.edu',
        logo: 'msu',
        location: 'Springfield, MO',
        period: 'Jan 2025 – Present',
        type: 'Part-time',
        description: 'Delivering undergraduate mathematics instruction and student support within the Department of Mathematics at Missouri State University.',
        bullets: [
          'Delivered structured undergraduate mathematics lectures, guiding students through rigorous problem-solving and logical reasoning.',
          'Provided individualized support to students facing difficulty with complex concepts, breaking material into clear and accessible steps.',
          'Led weekly office hours and review sessions, reinforcing course material and developing students analytical confidence.',
          'Evaluated student work with emphasis on correctness, clarity, and methodological consistency, maintaining detailed grading rubrics.',
        ],
      },
    ],
    education: [
      {
        id: 'edu-teach-1',
        degree: 'M.S. Mathematics and Graduate Certificate in Software Engineering',
        school: 'Missouri State University',
        schoolUrl: 'https://www.missouristate.edu',
        logo: 'msu_edu',
        location: 'Springfield, MO',
        period: 'Jan 2025 – Expected Dec 2026',
        gpa: '3.73 / 4.0',
        courses: ['Abstract Algebra I and II', 'Number Theory', 'Mathematical Probability', 'Applied Regression', 'Artificial Intelligence'],
      },
      {
        id: 'edu-teach-2',
        degree: 'B.Sc. Mathematics (Minor: Computer Science)',
        school: 'Covenant University',
        schoolUrl: 'https://covenantuniversity.edu.ng',
        logo: 'covenant',
        location: 'Ogun State, Nigeria',
        period: 'Sept 2019 – Sept 2023',
        gpa: '3.92 / 5.0',
        courses: ['Algorithms and Complexity Analysis', 'Theory of Computing', 'Object-Oriented Programming', 'Structured Programming'],
      },
    ],
    interests: [
      { icon: 'MdFunctions',         label: 'Pure Mathematics',      desc: 'Abstract algebra, number theory, and the beauty of mathematical proof for its own sake. I find the discipline of rigorous proof deeply satisfying.' },
      { icon: 'FaChalkboardTeacher', label: 'Mathematics Education', desc: 'Thinking about how to make mathematics genuinely accessible without sacrificing rigour. Currently developing my own pedagogical approach.' },
      { icon: 'FaLaptop',            label: 'Computational Math',    desc: 'Where mathematics meets computing: algorithms, numerical methods, and how machine learning connects to the mathematics I study.' },
      { icon: 'FaPray',              label: 'The Church',            desc: 'An active member of my church community. Faith is central to who I am and shapes how I approach teaching, mentorship, and community.' },
      { icon: 'FaFutbol',            label: 'Football',              desc: 'Lifelong football fan. I follow matches closely and find the tactical and data dimensions of the sport increasingly interesting.' },
      { icon: 'FaBook',              label: 'Reading',               desc: 'Particularly interested in the history of mathematics, philosophy of science, and academic writing on pedagogy and teaching practice.' },
    ],
    services: [
      {
        icon: 'FaChalkboardTeacher',
        title: 'Private Mathematics Tutoring',
        desc: 'One-on-one sessions built around where you actually are, not where you are supposed to be. I locate the conceptual gap and work from there until the material clicks.',
        deliverables: ['Pre-calculus and calculus', 'Linear algebra', 'Statistics and probability', 'Abstract algebra', 'Proof writing and logic'],
      },
      {
        icon: 'FaUsers',
        title: 'Group Study and Review Sessions',
        desc: 'Structured small-group sessions for exam preparation or weekly reinforcement. Designed to build analytical confidence over time through guided practice, not just content coverage.',
        deliverables: ['Problem-solving walkthroughs', 'Past paper and exam review', 'Concept reinforcement', 'Student Q&A sessions'],
      },
      {
        icon: 'FaBookOpen',
        title: 'Study Plan and Curriculum Design',
        desc: 'Custom learning roadmaps for mathematics students who want structure and direction. Whether preparing for a specific exam or working toward long-term mastery.',
        deliverables: ['Paced weekly study schedule', 'Resource recommendations', 'Milestone checkpoints', 'Topic sequencing and prioritization'],
      },
      {
        icon: 'FaClipboardList',
        title: 'Exam Preparation Coaching',
        desc: 'Targeted coaching for upcoming tests. I focus on the areas where you lose the most marks and build both understanding and exam technique in the available time.',
        deliverables: ['Topic triage and prioritization', 'Custom practice problem sets', 'Timed practice sessions', 'Error pattern analysis'],
      },
      {
        icon: 'FaLaptop',
        title: 'Educational Platform Development',
        desc: 'Web-based tools built for schools and educators. Student management systems, attendance trackers, result generators, and communication platforms based on real production experience.',
        deliverables: ['School management systems', 'Student portals', 'Assessment and grading tools', 'Staff and parent communication platforms'],
      },
    ],
    cvFile: '/CV_Teaching.pdf',
    cvLabel: 'Teaching and Academia CV',
  },

  data: {
    id: 'data',
    label: 'Data Science',
    portfolioStatement: 'You are viewing my Data Science portfolio',
    color: '#9333EA',
    accentBg: '#F5F0FF',
    accentBorder: '#D8B4FE',
    heroRoles: ['Data Science Student', 'Data Analyst', 'Applied Statistician', 'ML Enthusiast'],
    heroTagline: 'I turn numbers into decisions.',
    bio: `Mathematics graduate student (GPA 3.73) at Missouri State University, actively transitioning into data science and applied statistics. My background is an unusual combination: a Mathematics degree with a Computer Science minor, 3 years of backend software development, and ongoing graduate coursework in Mathematical Probability, Applied Regression, and Artificial Intelligence. I approach data problems with both statistical training and engineering discipline. Actively building Python and R proficiency to complement strong SQL and algorithmic foundations.`,
    highlights: [
      { value: '3.73', label: 'Graduate GPA'        },
      { value: '3.92', label: 'Undergrad GPA'       },
      { value: '3+',   label: 'Years Dev Experience' },
    ],
    skills: [
      {
        name: 'Statistical Reasoning',
        icon: 'FaChartLine',
        level: 'Advanced',
        desc: 'Strong mathematical foundation from undergraduate and graduate coursework: probability theory, applied regression, linear algebra, and discrete mathematics. Actively applying these to real data analysis problems.',
      },
      {
        name: 'Python',
        icon: 'SiPython',
        level: 'Beginner',
        desc: 'Actively developing Python for data analysis and scripting. Currently using it in graduate coursework at MSU and beginning to explore pandas, NumPy, and matplotlib.',
      },
      {
        name: 'SQL and Database Querying',
        icon: 'FaDatabase',
        level: 'Advanced',
        desc: '3 years of production experience with MySQL and MongoDB from professional software development. Skilled at writing queries, designing schemas, and ensuring data consistency in live systems.',
      },
      {
        name: 'Data Pipelines',
        icon: 'FaStream',
        level: 'Beginner',
        desc: 'Built structured data flows in production applications connecting users, payment events, and transaction records. Not yet experienced with tools like Spark or Airflow but actively learning.',
      },
      {
        name: 'Excel and Structured Data',
        icon: 'FaTable',
        level: 'Intermediate',
        desc: 'Comfortable with tabular data in Excel for analysis, validation, and reporting. Learning to move from spreadsheet-based workflows into Python-based pipelines.',
      },
      {
        name: 'Algorithms and Complexity',
        icon: 'FaCogs',
        level: 'Advanced',
        desc: 'Undergraduate coursework in Algorithms and Complexity Analysis at Covenant University. Understand Big-O notation, common data structures, and how computational cost scales with input size.',
      },
      {
        name: 'Artificial Intelligence',
        icon: 'FaRobot',
        level: 'Intermediate',
        desc: 'Graduate coursework in AI at Missouri State University. Familiar with foundational concepts including search algorithms, knowledge representation, and introductory machine learning. Still actively building depth.',
      },
      {
        name: 'R',
        icon: 'FaChartBar',
        level: 'Beginner',
        desc: 'Beginning to use R for statistical analysis in the context of my Applied Regression coursework at MSU. I am a beginner here and actively growing. Willing and motivated to develop this skill further.',
      },
    ],
    stack: ['Python', 'MySQL', 'MongoDB', 'R', 'JavaScript', 'Git', 'GitHub', 'Node.js', 'Express', 'React JS', 'LaTeX'],
    projectIds: [1, 2, 4, 5],
    experience: [
      {
        id: 'exp-data-1',
        role: 'Junior Software Developer',
        company: 'Techvibes International Limited',
        companyUrl: 'https://techvibes.africa',
        logo: 'techvibes',
        location: 'Abuja, Nigeria',
        period: 'Jan 2024 – Dec 2024',
        type: 'Full-time',
        description: 'Applied algorithmic thinking and structured data management to production software systems at a technology company serving schools across Nigeria.',
        bullets: [
          'Applied algorithmic thinking to implement backend logic for authentication, transaction workflows, and data validation, requiring structured analysis of edge cases and system constraints.',
          'Worked with MySQL databases to query, validate, and maintain data consistency across production systems, building hands-on experience with structured data management at scale.',
          'Collaborated cross-functionally to translate business requirements into clear, testable implementations.',
        ],
      },
      {
        id: 'exp-data-2',
        role: 'Graduate Teaching Assistant',
        company: 'Missouri State University',
        companyUrl: 'https://www.missouristate.edu',
        logo: 'msu',
        location: 'Springfield, MO',
        period: 'Jan 2025 – Present',
        type: 'Part-time',
        description: 'Teaching quantitative reasoning and mathematical problem-solving at the undergraduate level within the Mathematics Department.',
        bullets: [
          'Delivered structured undergraduate mathematics lectures, developing the ability to communicate complex quantitative concepts clearly to non-specialist audiences.',
          'Applied probability, statistics, and mathematical reasoning in a teaching context, which directly informs my data science communication approach.',
        ],
      },
    ],
    education: [
      {
        id: 'edu-data-1',
        degree: 'M.S. Mathematics and Graduate Certificate in Software Engineering',
        school: 'Missouri State University',
        schoolUrl: 'https://www.missouristate.edu',
        logo: 'msu_edu',
        location: 'Springfield, MO',
        period: 'Jan 2025 – Expected Dec 2026',
        gpa: '3.73 / 4.0',
        courses: ['Mathematical Probability', 'Applied Regression', 'Artificial Intelligence', 'Advanced Internet Programming'],
      },
      {
        id: 'edu-data-2',
        degree: 'B.Sc. Mathematics (Minor: Computer Science)',
        school: 'Covenant University',
        schoolUrl: 'https://covenantuniversity.edu.ng',
        logo: 'covenant',
        location: 'Ogun State, Nigeria',
        period: 'Sept 2019 – Sept 2023',
        gpa: '3.92 / 5.0',
        courses: ['Algorithms and Complexity Analysis', 'Theory of Computing', 'Object-Oriented Programming', 'Structured Programming'],
      },
    ],
    interests: [
      { icon: 'FaChartLine',   label: 'Statistical Modelling', desc: 'Regression models, probability distributions, and applying statistical theory to real-world datasets. Currently the focus of my graduate coursework.' },
      { icon: 'FaRobot',       label: 'Machine Learning',      desc: 'Supervised and unsupervised learning, model evaluation, and the mathematics behind the algorithms. Actively learning and genuinely excited about this space.' },
      { icon: 'MdFunctions',   label: 'Applied Mathematics',   desc: 'How abstract mathematical structures show up in data science, optimisation, and algorithm design. My Mathematics background feels increasingly relevant here.' },
      { icon: 'FaPray',        label: 'The Church',            desc: 'An active member of my church community. Faith shapes how I approach work, relationships, and my broader purpose.' },
      { icon: 'FaFutbol',      label: 'Football',              desc: 'Lifelong football fan and increasingly interested in sports analytics and how data is reshaping how we understand the game.' },
      { icon: 'FaBookOpen',    label: 'Continuous Learning',   desc: 'Online courses, research papers, and working through real datasets. Always building toward the next skill on the list.' },
    ],
    services: [
      {
        icon: 'FaDatabase',
        title: 'Database Design and Querying',
        desc: 'Relational database design, normalized schemas, and optimized SQL queries built from 3 years of production experience with MySQL and MongoDB in live applications.',
        deliverables: ['Schema and data model design', 'SQL query optimization', 'Data normalization', 'MySQL and MongoDB', 'Migration and seed support'],
      },
      {
        icon: 'FaChartLine',
        title: 'Data Analysis and Reporting',
        desc: 'Structured analysis of datasets using SQL and Python. I extract patterns, validate hypotheses, and translate findings into clear, actionable reports grounded in statistical reasoning.',
        deliverables: ['Exploratory data analysis', 'Statistical summaries', 'Data cleaning and validation', 'Written findings and interpretation'],
      },
      {
        icon: 'FaCode',
        title: 'Data-Driven Web Applications',
        desc: 'Full-stack applications where the data layer is central to the product. Dashboards, reporting tools, and systems built so the numbers are always accessible, accurate, and fast.',
        deliverables: ['React frontend with data displays', 'Node.js backend with analytics logic', 'Database integration', 'Charts and visualizations'],
      },
      {
        icon: 'FaCogs',
        title: 'Backend and API Integration',
        desc: 'APIs that serve structured data cleanly to frontends or third-party consumers. Input validation, authentication, and reliable documentation included as standard.',
        deliverables: ['REST API design', 'Data validation and sanitization', 'JWT authentication', 'Third-party API connections', 'Endpoint documentation'],
      },
      {
        icon: 'FaGlobe',
        title: 'Business Websites with Analytics Needs',
        desc: 'Professional websites for businesses that need more than a static site. Contact forms, lead capture, and integration with analytics tools to understand who is visiting and why.',
        deliverables: ['Responsive business website', 'Contact and lead capture forms', 'Analytics integration', 'SEO fundamentals', 'Fast load performance'],
      },
    ],
    cvFile: '/CV_DataScience.pdf',
    cvLabel: 'Data Science CV',
  },
};

const TrackContext = createContext(null);

export const TrackProvider = ({ children }) => {
  const [activeTrack, setActiveTrack] = useState('software');
  const track = TRACKS[activeTrack];

  return (
    <TrackContext.Provider value={{ activeTrack, setActiveTrack, track, TRACKS }}>
      {children}
    </TrackContext.Provider>
  );
};

export const useTrack = () => useContext(TrackContext);
